// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/api/mailto-handler": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/developer": {
    params: {};
  };
  "/mail": {
    params: {};
  };
  "/mail/create": {
    params: {};
  };
  "/mail/compose": {
    params: {};
  };
  "/mail/under-construction/:path": {
    params: {
      "path": string;
    };
  };
  "/mail/:folder": {
    params: {
      "folder": string;
    };
  };
  "/settings": {
    params: {};
  };
  "/settings/appearance": {
    params: {};
  };
  "/settings/general": {
    params: {};
  };
  "/settings/labels": {
    params: {};
  };
  "/settings/notifications": {
    params: {};
  };
  "/settings/privacy": {
    params: {};
  };
  "/settings/security": {
    params: {};
  };
  "/settings/shortcuts": {
    params: {};
  };
  "/settings/*": {
    params: {
      "*": string;
    };
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/api/mailto-handler" | "/login" | "/developer" | "/mail" | "/mail/create" | "/mail/compose" | "/mail/under-construction/:path" | "/mail/:folder" | "/settings" | "/settings/appearance" | "/settings/general" | "/settings/labels" | "/settings/notifications" | "/settings/privacy" | "/settings/security" | "/settings/shortcuts" | "/settings/*" | "/*";
  };
  "page.tsx": {
    id: "page";
    page: "/";
  };
  "mailto-handler.ts": {
    id: "mailto-handler";
    page: "/api/mailto-handler";
  };
  "(auth)/login/page.tsx": {
    id: "(auth)/login/page";
    page: "/login";
  };
  "(routes)/layout.tsx": {
    id: "(routes)/layout";
    page: "/developer" | "/mail" | "/mail/create" | "/mail/compose" | "/mail/under-construction/:path" | "/mail/:folder" | "/settings" | "/settings/appearance" | "/settings/general" | "/settings/labels" | "/settings/notifications" | "/settings/privacy" | "/settings/security" | "/settings/shortcuts" | "/settings/*" | "/*";
  };
  "(routes)/developer/page.tsx": {
    id: "(routes)/developer/page";
    page: "/developer";
  };
  "(routes)/mail/layout.tsx": {
    id: "(routes)/mail/layout";
    page: "/mail" | "/mail/create" | "/mail/compose" | "/mail/under-construction/:path" | "/mail/:folder";
  };
  "(routes)/mail/page.tsx": {
    id: "(routes)/mail/page";
    page: "/mail";
  };
  "(routes)/mail/create/page.tsx": {
    id: "(routes)/mail/create/page";
    page: "/mail/create";
  };
  "(routes)/mail/compose/page.tsx": {
    id: "(routes)/mail/compose/page";
    page: "/mail/compose";
  };
  "(routes)/mail/under-construction/[path]/page.tsx": {
    id: "(routes)/mail/under-construction/[path]/page";
    page: "/mail/under-construction/:path";
  };
  "(routes)/mail/[folder]/page.tsx": {
    id: "(routes)/mail/[folder]/page";
    page: "/mail/:folder";
  };
  "(routes)/settings/layout.tsx": {
    id: "(routes)/settings/layout";
    page: "/settings" | "/settings/appearance" | "/settings/general" | "/settings/labels" | "/settings/notifications" | "/settings/privacy" | "/settings/security" | "/settings/shortcuts" | "/settings/*";
  };
  "(routes)/settings/page.tsx": {
    id: "(routes)/settings/page";
    page: "/settings";
  };
  "(routes)/settings/appearance/page.tsx": {
    id: "(routes)/settings/appearance/page";
    page: "/settings/appearance";
  };
  "(routes)/settings/general/page.tsx": {
    id: "(routes)/settings/general/page";
    page: "/settings/general";
  };
  "(routes)/settings/labels/page.tsx": {
    id: "(routes)/settings/labels/page";
    page: "/settings/labels";
  };
  "(routes)/settings/notifications/page.tsx": {
    id: "(routes)/settings/notifications/page";
    page: "/settings/notifications";
  };
  "(routes)/settings/privacy/page.tsx": {
    id: "(routes)/settings/privacy/page";
    page: "/settings/privacy";
  };
  "(routes)/settings/security/page.tsx": {
    id: "(routes)/settings/security/page";
    page: "/settings/security";
  };
  "(routes)/settings/shortcuts/page.tsx": {
    id: "(routes)/settings/shortcuts/page";
    page: "/settings/shortcuts";
  };
  "(routes)/settings/[...settings]/page.tsx": {
    id: "(routes)/settings/[...settings]/page";
    page: "/settings/*";
  };
  "meta-files/not-found.ts": {
    id: "meta-files/not-found";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "page": typeof import("./app/page.tsx");
  "mailto-handler": typeof import("./app/mailto-handler.ts");
  "(auth)/login/page": typeof import("./app/(auth)/login/page.tsx");
  "(routes)/layout": typeof import("./app/(routes)/layout.tsx");
  "(routes)/developer/page": typeof import("./app/(routes)/developer/page.tsx");
  "(routes)/mail/layout": typeof import("./app/(routes)/mail/layout.tsx");
  "(routes)/mail/page": typeof import("./app/(routes)/mail/page.tsx");
  "(routes)/mail/create/page": typeof import("./app/(routes)/mail/create/page.tsx");
  "(routes)/mail/compose/page": typeof import("./app/(routes)/mail/compose/page.tsx");
  "(routes)/mail/under-construction/[path]/page": typeof import("./app/(routes)/mail/under-construction/[path]/page.tsx");
  "(routes)/mail/[folder]/page": typeof import("./app/(routes)/mail/[folder]/page.tsx");
  "(routes)/settings/layout": typeof import("./app/(routes)/settings/layout.tsx");
  "(routes)/settings/page": typeof import("./app/(routes)/settings/page.tsx");
  "(routes)/settings/appearance/page": typeof import("./app/(routes)/settings/appearance/page.tsx");
  "(routes)/settings/general/page": typeof import("./app/(routes)/settings/general/page.tsx");
  "(routes)/settings/labels/page": typeof import("./app/(routes)/settings/labels/page.tsx");
  "(routes)/settings/notifications/page": typeof import("./app/(routes)/settings/notifications/page.tsx");
  "(routes)/settings/privacy/page": typeof import("./app/(routes)/settings/privacy/page.tsx");
  "(routes)/settings/security/page": typeof import("./app/(routes)/settings/security/page.tsx");
  "(routes)/settings/shortcuts/page": typeof import("./app/(routes)/settings/shortcuts/page.tsx");
  "(routes)/settings/[...settings]/page": typeof import("./app/(routes)/settings/[...settings]/page.tsx");
  "meta-files/not-found": typeof import("./app/meta-files/not-found.ts");
};